vich_uploader:
    db_driver: orm

    mappings:
       pizza_images:
           uri_prefix: '%app.path.pizza_images%'
           upload_destination: '%kernel.project_dir%/public%app.path.pizza_images%'
