version: '3.8'

volumes:
  database:
    driver: 'local'

services:
  webapp:
    image: nginx:alpine
    volumes:
      - .:/var/www/app:cahed
      - ./docker/dev/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app
      - database

  app:
    build:
      context: .
      dockerfile: docker/dev/php/Dockerfile
      args:
        PUID: ${PUID}
        PGID: ${PGID}
    depends_on:
      - database
    volumes:
      - .:/var/www/app

  database:
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: webmaster
      POSTGRES_USER: webmaster
      POSTGRES_DB: symfony
      PGDATA: /var/lib/postgresql/data/pgdata

